//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoJob.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int Id { get; set; }
        public string DisplayName { get; set; }
        public string Position { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Place { get; set; }
        public string Birthday { get; set; }
        public string Sex { get; set; }
        public string MarryStatus { get; set; }
        public string AimJob { get; set; }
        public string PersonalSkill { get; set; }
        public Nullable<int> IdLanguageSkill { get; set; }
        public Nullable<int> IdOfficeSkill { get; set; }
        public Nullable<int> IdDegree { get; set; }
        public Nullable<int> IdExperience { get; set; }
        public Nullable<int> IdAccount { get; set; }
        public byte[] Avatar { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Degree Degree { get; set; }
        public virtual Experience Experience { get; set; }
        public virtual LanguageSkill LanguageSkill { get; set; }
        public virtual OfficeSkill OfficeSkill { get; set; }
    }
}
