//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoJob.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {
        public int IdAccount { get; set; }
        public int IdJob { get; set; }
        public Nullable<int> STT { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Job Job { get; set; }
    }
}
